In [1]:
import numpy as np  # Step1: NumPyをインポート

# Step2: 行列AとBを定義（例として2x3と3x2の行列）
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# Step3: 行列の積を計算（@演算子またはnp.dotを使用）
product_matrix = A @ B  # または np.dot(A, B)

# Step4: 計算結果を表示
print("行列A:")
print(A)
print("\n行列B:")
print(B)
print("\nA × B の結果:")
print(product_matrix)

# Step5: 計算結果の要素の最大値を求めて表示
max_value = np.max(product_matrix)
print("\n計算結果の最大値:", max_value)

行列A:
[[1 2 3]
 [4 5 6]]

行列B:
[[ 7  8]
 [ 9 10]
 [11 12]]

A × B の結果行列:
[[ 58  64]
 [139 154]]

結果行列の要素の最大値: 154
